name: Hardhat CI/CD

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

env:
  # default hardhat key, do not use this for prod
  PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  FORK_URL: https://rpc.goerli.linea.build
  ENCLAVE_IDENTITY_HELPER: "0x4DfeFC7d9b139D5DD5837075FFd7CB340994d6bc"
  FMSPC_TCB_HELPER: "0xd7e1EE3d83baa20eA9ee5c42BcCCEDA411E2F02F"
  X509_CRL_HELPER: "0x74a4A96787D23058A67d9799F4Ac62379a1a3136"
  X509_HELPER: "0xaa27A6a77D6F23b0346863E732beF8D0DaF7c61E"
  ENCLAVE_IDENTITY_DAO_PORTAL: "0xeAce48c11258Ec79c941Daee80343298dC084Be3"
  FMSPC_TCB_DAO_PORTAL: "0x1930D878D4BAbb10b2C20F65D84a54fdf709959A"
  PCS_DAO_PORTAL: "0xC4838158D29C7DB6D344dDB4C082dB0f30C8073e"

jobs:
  check:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile the contracts
        run: npx hardhat compile

      - name: Run test(s)
        run: npx hardhat test